### ISSUE TITLE
Node method for accessing morphological features

### ISSUE THREAD

**Issue by VincTheSecond** [udapi/udapi-python#12]
Node method for accessing morphological features

**Comment by martinpopel** [comment]
Yes, this is really needed and it is related to accessing the MISC attributes.

We need first to decide how the API should look like. This is related to all the languages (Python, Java, Perl), so maybe we can create an issue in https://github.com/udapi/udapi-common/issues
Just to make obvious what I mean by the API: one suggestion is to have (in Perl and similarly in Java and Python): `$node->raw_feats = 'Case=Nom|Number=Plur'` and `$node->feats->{Case} = 'Nom'`.

**Comment by VincTheSecond** [comment]
In the current version, raw features are available in `node.feats`.
I propose to create a method `feature` which take exactly one parameter - the name of the feature:
`if node.feature('Tense') == 'Past': ...`

**Comment by VincTheSecond** [comment]
In the current version, raw features are available as `node.feats`.
I propose to move this into `node.raw_feats`.
A new `node.feats` will be the dict with parsed features.

**Comment by martinpopel** [comment]
> In the current version, raw features are available as node.feats.
> I propose to move this into node.raw_feats.
> A new node.feats will be the dict with parsed features.

Yes, this is exactly what I meant. We just need to make sure that `raw_feats` stays synchronized with `feats`.
We can consider also your original suggestion that `feats` will stay the raw string and `feature` will be the dict.
We just should choose the same solution for MISC to be consistent, that is
`node.raw_misc = 'SpaceAfter=No|X=Y'` and `node.misc('X') = 'Y'`
or
`node.misc = 'SpaceAfter=No|X=Y'` and `node.misc2('X') = 'Y'`
but here I am not sure what should be an intuitive name for `misc2`.

**Comment by VincTheSecond** [comment]
Because of synchronization, I see two possible strategies:

1) The information will be stored only on one place (`node.feats`) and instead of a dict, there will be two methods `node.get_feature(feature_name)` and `node.set_feature(feature_name, feature_value)`. The methods will parse the "raw" data.

2) There will be methods `node.load_features()` and `node.dump_features()` which convert `node.feats` from/into dict.

**Comment by martinpopel** [comment]
I think dict is easiest to use (plus possibly the `is_*` methods from [Interset](https://metacpan.org/pod/Lingua::Interset::FeatureStructure#is_abbreviation) but here I am not sure if we should introduce them).
On the other hand, there may be many scenarios which do not need to access the features, so for speed it is better to deserialize the features lazily.

So my suggestion is that each node (or all nodes together?) will internally remember whether `raw_feats` were deserialized into the dict or not. If not, `node.raw_feats` will return the string. By accessing `node.feats`, the deserialization will happen. Since then accessing `node.raw_feats` will serialize the dict (without any caching?).

Another question is whether we want to validate the feature names and values. Again there should be a fast&robust way and slower&strict way. If validation is on, it should happen as soon as possible, i.e. during the assignment `node.feat('Case')='Nom'`, not just during the serialization.
