### ISSUE TITLE
SetSpaceAfter with ...

### ISSUE THREAD

**Issue by ftyers** [udapi/udapi-python#67]
I'm working on a treebank where there are sentences ending in `...`. 

`ud.SetSpaceAfter` does not mark these with `SpaceAfter=No`. 

It could be added, but would be difficult without including `import re`.

Actually maybe you could do something like:
```python
            # for ...
            if ''.join(list(set(node.form))) in self.not_after or ''.join(list(set(next_form))) in not_before:
                self.mark_no_space(node)
```

**Comment by martinpopel** [comment]
Hi Fran!

* Do you have the original raw text of that treebank? If yes, you could use [ud.SetSpaceAfterFromText](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/setspaceafterfromtext.py). If there are other differences than spaces (between the raw text and the existing annotation), you can try [ud.ComplyWithText](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/complywithtext.py).
* So you don't have the raw text, but you know that in a given language the ellipsis (either written as three dots or as U+2026 (…)) is **never preceded by a space**? BTW: in English, [it depends on the chosen style](https://english.stackexchange.com/questions/26240/what-is-the-proper-way-of-using-triple-dots-and-spaces-before-after-them), e.g. the [AP Stylebook says](https://www.grammarly.com/blog/ellipsis/) to treat the ellipsis as a three-letter word, with spaces on either side of the ellipsis but no spaces between the dots. 
* Does the rule holds only for sentence-final ellipsis or for any ellipsis? Does that language use space also **after** ellipsis?
* If needed, we could `import re` in [ud.SetSpaceAfter](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/setspaceafter.py). It is imported in many other Udapi blocks.
* Your code does not make sense because `"".join(list(set("abcbc"))) == "bca"` (set of unique characters in a random order) and `"substring" in "string"` is a Python check for substring, not for subset. I guess you wanted to write `if all(char in self.not_after for char in node.form) or all(char in self.not_before for char in next_form)`. This would match not only `...`, but also `???`, `!!?`, `)]` etc. That seems ok, most of such tokens are not usually preceded by a space in most styles and languages (this block is not suitable for French anyway). However, it would match also emoticons such as `:)` or `;)`, but not `:-)` because `-` is not included in the default `not_before`.

* Maybe we want to use `SpaceAfter=No` only where it is highly probable. To keep it simple and allow specifying the `not_before` and `not_after` parameters from the command line, I suggest:
`not_after='¡ ¿ ( [ { „'`
`not_before=' . , ; : ! ? } ] ) ?? ??? !! !!! ... …'`
`self.not_after = not_after.split(' ')`
`self.not_before = not_before.split(' ')`
Thus, `self.not_after` and `self.not_before` won't be strings, but lists. The code `if node.form in self.not_after or next_form in not_before` can be kept without any changes.
If you agree, I'll make the PR (the block needs a bit more documentation).

**Comment by ftyers** [comment]
Hi Martin :)

Yes, I have the original text, I didn't know about ud.SetSpaceAfterFromText, I'll check it out. But other than that I think allowing multicharacter punctuation tokens in the `not_before` and `not_after` is the best bet.

**Comment by martinpopel** [comment]
I finally fixed this issue as suggested above, so `not_after` and `not_before` is a space-separated list of word forms.
Newly, there is a simple way how to add just a few forms to the lists: `udapy ud.SetSpaceAfter extra_not_before="- ?. >" extra_not_after="- <"`
I've also improved the heuristics and added an English-specific subclass [ud.en.SetSpaceAfter](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/en/setspaceafter.py) as a source of inspiration. 
BTW: On UD_English-EWT dev-set it has P/R/F1 =  91.30% / 86.88% / 89.04% in re-constructing the `SpaceAfter` attribute and it seems most of the errors are either unclear/edge cases or typographic errors in the original text.
On UD_Czech-PDT dev-set P/R/F1 = 96.31% / 92.94% / 94.59% (which could be easily further improved with a Czech-specific block).
