### ISSUE TITLE
how to use REGEX in queries like...

### ISSUE THREAD

**Issue by arademaker** [udapi/udapi-python#91]
```
% awk '$2 ~ /^[A-Z]\.$/' *.conllu
````

maybe something like `~=` below?

```
% cat documents/*.conllu | udapy -q util.Eval node='if (node.form ~= "^[A-Z]\.$"): node.draw(attributes="form,lemma,upos,feats")
```

**Comment by martinpopel** [comment]
This is Python, so just use `re.match("[A-Z]\.$", node.form)` instead of `(node.form ~= "^[A-Z]\.$")`.
Blocks `util.Eval` and `util.Mark` already include `import re`.
Note that the initial `^` is not needed [in `re.match` (unlike `re.search`)](https://docs.python.org/3/library/re.html#search-vs-match).

BTW: `util.Mark` may be also useful here:
```
cat documents/*.conllu | udapy -qTMA util.Mark node='re.match("[A-Z]\.$", node.form)' | less -R
```
